# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_ARCHIVE_GID "-1")
set(CPACK_ARCHIVE_UID "-1")
set(CPACK_BUILD_SOURCE_DIRS "C:/Users/Jozh/repos/Jujo.StreamServer;C:/Users/Jozh/repos/Jujo.StreamServer")
set(CPACK_CMAKE_GENERATOR "Visual Studio 18 2026")
set(CPACK_COMPONENTS_ALL "Unspecified;application;assets;audio;autostart;dxgi;firewall;sudovda")
set(CPACK_COMPONENT_APPLICATION_DEPENDS "assets")
set(CPACK_COMPONENT_APPLICATION_DESCRIPTION "Vibepollo main application and required components.")
set(CPACK_COMPONENT_APPLICATION_DISPLAY_NAME "Vibepollo")
set(CPACK_COMPONENT_APPLICATION_GROUP "Core")
set(CPACK_COMPONENT_APPLICATION_REQUIRED "true")
set(CPACK_COMPONENT_ASSETS_DESCRIPTION "Shaders, default box art, and web UI.")
set(CPACK_COMPONENT_ASSETS_DISPLAY_NAME "Required Assets")
set(CPACK_COMPONENT_ASSETS_GROUP "Core")
set(CPACK_COMPONENT_ASSETS_REQUIRED "true")
set(CPACK_COMPONENT_AUDIO_DESCRIPTION "CLI tool providing information about sound devices.")
set(CPACK_COMPONENT_AUDIO_DISPLAY_NAME "audio-info")
set(CPACK_COMPONENT_AUDIO_GROUP "Tools")
set(CPACK_COMPONENT_AUTOSTART_DESCRIPTION "If enabled, launches Vibepollo automatically on system startup.")
set(CPACK_COMPONENT_AUTOSTART_DISPLAY_NAME "Launch on Startup")
set(CPACK_COMPONENT_AUTOSTART_GROUP "Core")
set(CPACK_COMPONENT_DXGI_DESCRIPTION "CLI tool providing information about graphics cards and displays.")
set(CPACK_COMPONENT_DXGI_DISPLAY_NAME "dxgi-info")
set(CPACK_COMPONENT_DXGI_GROUP "Tools")
set(CPACK_COMPONENT_FIREWALL_DESCRIPTION "Scripts to enable or disable firewall rules.")
set(CPACK_COMPONENT_FIREWALL_DISPLAY_NAME "Add Firewall Exclusions")
set(CPACK_COMPONENT_FIREWALL_GROUP "Scripts")
set(CPACK_COMPONENT_GROUP_CORE_EXPANDED "true")
set(CPACK_COMPONENT_SUDOVDA_DESCRIPTION "Driver required for Virtual Display to function.")
set(CPACK_COMPONENT_SUDOVDA_DISPLAY_NAME "SudoVDA")
set(CPACK_COMPONENT_SUDOVDA_GROUP "Drivers")
set(CPACK_COMPONENT_SUDOVDA_REQUIRED "true")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "C:/msys64/ucrt64/share/cmake/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "Vibepollo built using CMake")
set(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE "ON")
set(CPACK_GENERATOR "7Z;ZIP")
set(CPACK_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALLED_DIRECTORIES "C:/Users/Jozh/repos/Jujo.StreamServer;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "C:/Program Files (x86)/Vibepollo")
set(CPACK_MODULE_PATH "C:/Users/Jozh/repos/Jujo.StreamServer/cmake")
set(CPACK_NSIS_DISPLAY_NAME "Apollo")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES64")
set(CPACK_NSIS_PACKAGE_NAME "Apollo")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OUTPUT_CONFIG_FILE "C:/Users/Jozh/repos/Jujo.StreamServer/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "https://github.com/Nonary/Vibepollo/issues")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION "Self-hosted game stream host for Moonlight")
set(CPACK_PACKAGE_DESCRIPTION_FILE "C:/msys64/ucrt64/share/cmake/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Self-hosted game stream host for Moonlight")
set(CPACK_PACKAGE_DIRECTORY "C:/Users/Jozh/repos/Jujo.StreamServer/cpack_artifacts")
set(CPACK_PACKAGE_FILE_NAME "Vibepollo-0.0.0.0-Source")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://github.com/Nonary/Vibepollo")
set(CPACK_PACKAGE_ICON "C:/Users/Jozh/repos/Jujo.StreamServer\\apollo.ico")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "Apollo")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "Apollo")
set(CPACK_PACKAGE_NAME "Vibepollo")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Nonary")
set(CPACK_PACKAGE_VERSION "0.0.0.0")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "0")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_RESOURCE_FILE_LICENSE "C:/Users/Jozh/repos/Jujo.StreamServer/packaging/windows/LICENSE.rtf")
set(CPACK_RESOURCE_FILE_README "C:/msys64/ucrt64/share/cmake/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "C:/msys64/ucrt64/share/cmake/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_7Z "ON")
set(CPACK_SOURCE_GENERATOR "7Z;ZIP")
set(CPACK_SOURCE_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "C:/Users/Jozh/repos/Jujo.StreamServer;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "C:/Users/Jozh/repos/Jujo.StreamServer/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "Vibepollo-0.0.0.0-Source")
set(CPACK_SOURCE_TOPLEVEL_TAG "win64-Source")
set(CPACK_SOURCE_ZIP "ON")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "win64")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "win64-Source")
set(CPACK_WIX_CANDLE_EXTRA_FLAGS "-dBinDir=C:/Users/Jozh/repos/Jujo.StreamServer;-dVibepolloAppId=Nonary.Vibepollo")
set(CPACK_WIX_CULTURES "en-US")
set(CPACK_WIX_EXTENSIONS "WixUtilExtension;WixFirewallExtension")
set(CPACK_WIX_EXTRA_SOURCES "C:/Users/Jozh/repos/Jujo.StreamServer/packaging/windows/wix/custom_actions.wxs")
set(CPACK_WIX_LICENSE_RTF "C:/Users/Jozh/repos/Jujo.StreamServer/packaging/windows/LICENSE.rtf")
set(CPACK_WIX_LIGHT_EXTRA_FLAGS "-b;MyScripts=C:/Users/Jozh/repos/Jujo.StreamServer/packaging/windows/wix;-b;PayloadRoot=C:/Users/Jozh/repos/Jujo.StreamServer/wix_payload/")
set(CPACK_WIX_PATCH_FILE "C:/Users/Jozh/repos/Jujo.StreamServer/packaging/windows/wix/patch_custom_actions.wxs")
set(CPACK_WIX_PRODUCT_GUID "ADA3020C-727E-5C83-91F6-38FCC7E7122C")
set(CPACK_WIX_PRODUCT_ICON "C:/Users/Jozh/repos/Jujo.StreamServer/src_assets/common/assets/web/public/images/apollo.ico")
set(CPACK_WIX_PRODUCT_VERSION "0.0.0.0")
set(CPACK_WIX_PROGRAM_MENU_FOLDER "Vibepollo")
set(CPACK_WIX_PROPERTY_ARPCOMMENTS "Self-hosted game stream host for Moonlight")
set(CPACK_WIX_PROPERTY_ARPURLINFOABOUT "https://github.com/Nonary/Vibepollo")
set(CPACK_WIX_SIZEOF_VOID_P "8")
set(CPACK_WIX_TEMPLATE "C:/Users/Jozh/repos/Jujo.StreamServer/packaging/windows/wix/WIX.template.in")
set(CPACK_WIX_UPGRADE_GUID "{E3FA501A-85F8-4187-85A7-D6E6BDC7EDA1}")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "C:/Users/Jozh/repos/Jujo.StreamServer/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
