/**
 * @file src/platform/windows/version_rc.h.in
 * @brief Generated by CMake. Do not edit manually.
 * Provides version and metadata macros for the Windows resource compiler.
 */
#pragma once

/* Integer values for FILEVERSION / PRODUCTVERSION */
#define PROJECT_VERSION_MAJOR 1
#define PROJECT_VERSION_MINOR 0
#define PROJECT_VERSION_PATCH 28

/* String values — used via TOSTRING() macro in the .rc file */
#define PROJECT_VERSION 1.0.28-test.4
#define PROJECT_NAME Jujo.StreamServer
#define PROJECT_VENDOR Jujo.Stream

/* Icon path — used directly as a filename token in the ICON resource */
#define PROJECT_ICON_PATH "C:/Users/Jozh/repos/Jujo.StreamServer/jujo_stream_server.ico"
